# https://github.com/brigade/overcommit/blob/master/config/default.yml
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration

verify_plugin_signatures: false

CommitMsg:
  CapitalizedSubject:
    enabled: false

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bin/rubocop-precommit']

  TrailingWhitespace:
    enabled: true

  RakeStatsSave:
    enabled: false # muito lento

PrePush:
  RSpec:
    enabled: false
